import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../../app/globals.css'
import '../globals.css'
import { BottomBar ,LeftSidebar,RightSidebar,TopBar } from '@/core/components'

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
        <TopBar />
        <main>
          <LeftSidebar />
          <section className="main-container">
            <div className="w-full max-w-4xl">
          {children}
            </div>
          </section>
          <RightSidebar />
        </main>
        <BottomBar />
      </html>
    </ClerkProvider>
  )
}
